global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'catalog-service'
    static_configs:
      - targets: ['catalog-service:8080']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']