// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/neokofg/go-pet-microservices/catalog-service/ent/item"
	"github.com/neokofg/go-pet-microservices/catalog-service/ent/predicate"
)

// ItemUpdate is the builder for updating Item entities.
type ItemUpdate struct {
	config
	hooks    []Hook
	mutation *ItemMutation
}

// Where appends a list predicates to the ItemUpdate builder.
func (iu *ItemUpdate) Where(ps ...predicate.Item) *ItemUpdate {
	iu.mutation.Where(ps...)
	return iu
}

// SetTitle sets the "title" field.
func (iu *ItemUpdate) SetTitle(s string) *ItemUpdate {
	iu.mutation.SetTitle(s)
	return iu
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (iu *ItemUpdate) SetNillableTitle(s *string) *ItemUpdate {
	if s != nil {
		iu.SetTitle(*s)
	}
	return iu
}

// SetDescription sets the "description" field.
func (iu *ItemUpdate) SetDescription(s string) *ItemUpdate {
	iu.mutation.SetDescription(s)
	return iu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (iu *ItemUpdate) SetNillableDescription(s *string) *ItemUpdate {
	if s != nil {
		iu.SetDescription(*s)
	}
	return iu
}

// ClearDescription clears the value of the "description" field.
func (iu *ItemUpdate) ClearDescription() *ItemUpdate {
	iu.mutation.ClearDescription()
	return iu
}

// SetTags sets the "tags" field.
func (iu *ItemUpdate) SetTags(s []string) *ItemUpdate {
	iu.mutation.SetTags(s)
	return iu
}

// AppendTags appends s to the "tags" field.
func (iu *ItemUpdate) AppendTags(s []string) *ItemUpdate {
	iu.mutation.AppendTags(s)
	return iu
}

// ClearTags clears the value of the "tags" field.
func (iu *ItemUpdate) ClearTags() *ItemUpdate {
	iu.mutation.ClearTags()
	return iu
}

// SetImageURL sets the "image_url" field.
func (iu *ItemUpdate) SetImageURL(s string) *ItemUpdate {
	iu.mutation.SetImageURL(s)
	return iu
}

// SetNillableImageURL sets the "image_url" field if the given value is not nil.
func (iu *ItemUpdate) SetNillableImageURL(s *string) *ItemUpdate {
	if s != nil {
		iu.SetImageURL(*s)
	}
	return iu
}

// ClearImageURL clears the value of the "image_url" field.
func (iu *ItemUpdate) ClearImageURL() *ItemUpdate {
	iu.mutation.ClearImageURL()
	return iu
}

// SetRating sets the "rating" field.
func (iu *ItemUpdate) SetRating(f float64) *ItemUpdate {
	iu.mutation.ResetRating()
	iu.mutation.SetRating(f)
	return iu
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (iu *ItemUpdate) SetNillableRating(f *float64) *ItemUpdate {
	if f != nil {
		iu.SetRating(*f)
	}
	return iu
}

// AddRating adds f to the "rating" field.
func (iu *ItemUpdate) AddRating(f float64) *ItemUpdate {
	iu.mutation.AddRating(f)
	return iu
}

// SetReviewCount sets the "review_count" field.
func (iu *ItemUpdate) SetReviewCount(i int) *ItemUpdate {
	iu.mutation.ResetReviewCount()
	iu.mutation.SetReviewCount(i)
	return iu
}

// SetNillableReviewCount sets the "review_count" field if the given value is not nil.
func (iu *ItemUpdate) SetNillableReviewCount(i *int) *ItemUpdate {
	if i != nil {
		iu.SetReviewCount(*i)
	}
	return iu
}

// AddReviewCount adds i to the "review_count" field.
func (iu *ItemUpdate) AddReviewCount(i int) *ItemUpdate {
	iu.mutation.AddReviewCount(i)
	return iu
}

// SetCreatedAt sets the "created_at" field.
func (iu *ItemUpdate) SetCreatedAt(t time.Time) *ItemUpdate {
	iu.mutation.SetCreatedAt(t)
	return iu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (iu *ItemUpdate) SetNillableCreatedAt(t *time.Time) *ItemUpdate {
	if t != nil {
		iu.SetCreatedAt(*t)
	}
	return iu
}

// SetUpdatedAt sets the "updated_at" field.
func (iu *ItemUpdate) SetUpdatedAt(t time.Time) *ItemUpdate {
	iu.mutation.SetUpdatedAt(t)
	return iu
}

// Mutation returns the ItemMutation object of the builder.
func (iu *ItemUpdate) Mutation() *ItemMutation {
	return iu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (iu *ItemUpdate) Save(ctx context.Context) (int, error) {
	iu.defaults()
	return withHooks(ctx, iu.sqlSave, iu.mutation, iu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (iu *ItemUpdate) SaveX(ctx context.Context) int {
	affected, err := iu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (iu *ItemUpdate) Exec(ctx context.Context) error {
	_, err := iu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iu *ItemUpdate) ExecX(ctx context.Context) {
	if err := iu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (iu *ItemUpdate) defaults() {
	if _, ok := iu.mutation.UpdatedAt(); !ok {
		v := item.UpdateDefaultUpdatedAt()
		iu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (iu *ItemUpdate) check() error {
	if v, ok := iu.mutation.Title(); ok {
		if err := item.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Item.title": %w`, err)}
		}
	}
	return nil
}

func (iu *ItemUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := iu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(item.Table, item.Columns, sqlgraph.NewFieldSpec(item.FieldID, field.TypeString))
	if ps := iu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := iu.mutation.Title(); ok {
		_spec.SetField(item.FieldTitle, field.TypeString, value)
	}
	if value, ok := iu.mutation.Description(); ok {
		_spec.SetField(item.FieldDescription, field.TypeString, value)
	}
	if iu.mutation.DescriptionCleared() {
		_spec.ClearField(item.FieldDescription, field.TypeString)
	}
	if value, ok := iu.mutation.Tags(); ok {
		_spec.SetField(item.FieldTags, field.TypeJSON, value)
	}
	if value, ok := iu.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, item.FieldTags, value)
		})
	}
	if iu.mutation.TagsCleared() {
		_spec.ClearField(item.FieldTags, field.TypeJSON)
	}
	if value, ok := iu.mutation.ImageURL(); ok {
		_spec.SetField(item.FieldImageURL, field.TypeString, value)
	}
	if iu.mutation.ImageURLCleared() {
		_spec.ClearField(item.FieldImageURL, field.TypeString)
	}
	if value, ok := iu.mutation.Rating(); ok {
		_spec.SetField(item.FieldRating, field.TypeFloat64, value)
	}
	if value, ok := iu.mutation.AddedRating(); ok {
		_spec.AddField(item.FieldRating, field.TypeFloat64, value)
	}
	if value, ok := iu.mutation.ReviewCount(); ok {
		_spec.SetField(item.FieldReviewCount, field.TypeInt, value)
	}
	if value, ok := iu.mutation.AddedReviewCount(); ok {
		_spec.AddField(item.FieldReviewCount, field.TypeInt, value)
	}
	if value, ok := iu.mutation.CreatedAt(); ok {
		_spec.SetField(item.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := iu.mutation.UpdatedAt(); ok {
		_spec.SetField(item.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, iu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{item.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	iu.mutation.done = true
	return n, nil
}

// ItemUpdateOne is the builder for updating a single Item entity.
type ItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ItemMutation
}

// SetTitle sets the "title" field.
func (iuo *ItemUpdateOne) SetTitle(s string) *ItemUpdateOne {
	iuo.mutation.SetTitle(s)
	return iuo
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (iuo *ItemUpdateOne) SetNillableTitle(s *string) *ItemUpdateOne {
	if s != nil {
		iuo.SetTitle(*s)
	}
	return iuo
}

// SetDescription sets the "description" field.
func (iuo *ItemUpdateOne) SetDescription(s string) *ItemUpdateOne {
	iuo.mutation.SetDescription(s)
	return iuo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (iuo *ItemUpdateOne) SetNillableDescription(s *string) *ItemUpdateOne {
	if s != nil {
		iuo.SetDescription(*s)
	}
	return iuo
}

// ClearDescription clears the value of the "description" field.
func (iuo *ItemUpdateOne) ClearDescription() *ItemUpdateOne {
	iuo.mutation.ClearDescription()
	return iuo
}

// SetTags sets the "tags" field.
func (iuo *ItemUpdateOne) SetTags(s []string) *ItemUpdateOne {
	iuo.mutation.SetTags(s)
	return iuo
}

// AppendTags appends s to the "tags" field.
func (iuo *ItemUpdateOne) AppendTags(s []string) *ItemUpdateOne {
	iuo.mutation.AppendTags(s)
	return iuo
}

// ClearTags clears the value of the "tags" field.
func (iuo *ItemUpdateOne) ClearTags() *ItemUpdateOne {
	iuo.mutation.ClearTags()
	return iuo
}

// SetImageURL sets the "image_url" field.
func (iuo *ItemUpdateOne) SetImageURL(s string) *ItemUpdateOne {
	iuo.mutation.SetImageURL(s)
	return iuo
}

// SetNillableImageURL sets the "image_url" field if the given value is not nil.
func (iuo *ItemUpdateOne) SetNillableImageURL(s *string) *ItemUpdateOne {
	if s != nil {
		iuo.SetImageURL(*s)
	}
	return iuo
}

// ClearImageURL clears the value of the "image_url" field.
func (iuo *ItemUpdateOne) ClearImageURL() *ItemUpdateOne {
	iuo.mutation.ClearImageURL()
	return iuo
}

// SetRating sets the "rating" field.
func (iuo *ItemUpdateOne) SetRating(f float64) *ItemUpdateOne {
	iuo.mutation.ResetRating()
	iuo.mutation.SetRating(f)
	return iuo
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (iuo *ItemUpdateOne) SetNillableRating(f *float64) *ItemUpdateOne {
	if f != nil {
		iuo.SetRating(*f)
	}
	return iuo
}

// AddRating adds f to the "rating" field.
func (iuo *ItemUpdateOne) AddRating(f float64) *ItemUpdateOne {
	iuo.mutation.AddRating(f)
	return iuo
}

// SetReviewCount sets the "review_count" field.
func (iuo *ItemUpdateOne) SetReviewCount(i int) *ItemUpdateOne {
	iuo.mutation.ResetReviewCount()
	iuo.mutation.SetReviewCount(i)
	return iuo
}

// SetNillableReviewCount sets the "review_count" field if the given value is not nil.
func (iuo *ItemUpdateOne) SetNillableReviewCount(i *int) *ItemUpdateOne {
	if i != nil {
		iuo.SetReviewCount(*i)
	}
	return iuo
}

// AddReviewCount adds i to the "review_count" field.
func (iuo *ItemUpdateOne) AddReviewCount(i int) *ItemUpdateOne {
	iuo.mutation.AddReviewCount(i)
	return iuo
}

// SetCreatedAt sets the "created_at" field.
func (iuo *ItemUpdateOne) SetCreatedAt(t time.Time) *ItemUpdateOne {
	iuo.mutation.SetCreatedAt(t)
	return iuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (iuo *ItemUpdateOne) SetNillableCreatedAt(t *time.Time) *ItemUpdateOne {
	if t != nil {
		iuo.SetCreatedAt(*t)
	}
	return iuo
}

// SetUpdatedAt sets the "updated_at" field.
func (iuo *ItemUpdateOne) SetUpdatedAt(t time.Time) *ItemUpdateOne {
	iuo.mutation.SetUpdatedAt(t)
	return iuo
}

// Mutation returns the ItemMutation object of the builder.
func (iuo *ItemUpdateOne) Mutation() *ItemMutation {
	return iuo.mutation
}

// Where appends a list predicates to the ItemUpdate builder.
func (iuo *ItemUpdateOne) Where(ps ...predicate.Item) *ItemUpdateOne {
	iuo.mutation.Where(ps...)
	return iuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (iuo *ItemUpdateOne) Select(field string, fields ...string) *ItemUpdateOne {
	iuo.fields = append([]string{field}, fields...)
	return iuo
}

// Save executes the query and returns the updated Item entity.
func (iuo *ItemUpdateOne) Save(ctx context.Context) (*Item, error) {
	iuo.defaults()
	return withHooks(ctx, iuo.sqlSave, iuo.mutation, iuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (iuo *ItemUpdateOne) SaveX(ctx context.Context) *Item {
	node, err := iuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (iuo *ItemUpdateOne) Exec(ctx context.Context) error {
	_, err := iuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iuo *ItemUpdateOne) ExecX(ctx context.Context) {
	if err := iuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (iuo *ItemUpdateOne) defaults() {
	if _, ok := iuo.mutation.UpdatedAt(); !ok {
		v := item.UpdateDefaultUpdatedAt()
		iuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (iuo *ItemUpdateOne) check() error {
	if v, ok := iuo.mutation.Title(); ok {
		if err := item.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Item.title": %w`, err)}
		}
	}
	return nil
}

func (iuo *ItemUpdateOne) sqlSave(ctx context.Context) (_node *Item, err error) {
	if err := iuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(item.Table, item.Columns, sqlgraph.NewFieldSpec(item.FieldID, field.TypeString))
	id, ok := iuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Item.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := iuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, item.FieldID)
		for _, f := range fields {
			if !item.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != item.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := iuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := iuo.mutation.Title(); ok {
		_spec.SetField(item.FieldTitle, field.TypeString, value)
	}
	if value, ok := iuo.mutation.Description(); ok {
		_spec.SetField(item.FieldDescription, field.TypeString, value)
	}
	if iuo.mutation.DescriptionCleared() {
		_spec.ClearField(item.FieldDescription, field.TypeString)
	}
	if value, ok := iuo.mutation.Tags(); ok {
		_spec.SetField(item.FieldTags, field.TypeJSON, value)
	}
	if value, ok := iuo.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, item.FieldTags, value)
		})
	}
	if iuo.mutation.TagsCleared() {
		_spec.ClearField(item.FieldTags, field.TypeJSON)
	}
	if value, ok := iuo.mutation.ImageURL(); ok {
		_spec.SetField(item.FieldImageURL, field.TypeString, value)
	}
	if iuo.mutation.ImageURLCleared() {
		_spec.ClearField(item.FieldImageURL, field.TypeString)
	}
	if value, ok := iuo.mutation.Rating(); ok {
		_spec.SetField(item.FieldRating, field.TypeFloat64, value)
	}
	if value, ok := iuo.mutation.AddedRating(); ok {
		_spec.AddField(item.FieldRating, field.TypeFloat64, value)
	}
	if value, ok := iuo.mutation.ReviewCount(); ok {
		_spec.SetField(item.FieldReviewCount, field.TypeInt, value)
	}
	if value, ok := iuo.mutation.AddedReviewCount(); ok {
		_spec.AddField(item.FieldReviewCount, field.TypeInt, value)
	}
	if value, ok := iuo.mutation.CreatedAt(); ok {
		_spec.SetField(item.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := iuo.mutation.UpdatedAt(); ok {
		_spec.SetField(item.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Item{config: iuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, iuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{item.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	iuo.mutation.done = true
	return _node, nil
}
