// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/neokofg/go-pet-microservices/catalog-service/ent/item"
	"github.com/neokofg/go-pet-microservices/catalog-service/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	itemFields := schema.Item{}.Fields()
	_ = itemFields
	// itemDescTitle is the schema descriptor for title field.
	itemDescTitle := itemFields[1].Descriptor()
	// item.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	item.TitleValidator = itemDescTitle.Validators[0].(func(string) error)
	// itemDescRating is the schema descriptor for rating field.
	itemDescRating := itemFields[5].Descriptor()
	// item.DefaultRating holds the default value on creation for the rating field.
	item.DefaultRating = itemDescRating.Default.(float64)
	// itemDescReviewCount is the schema descriptor for review_count field.
	itemDescReviewCount := itemFields[6].Descriptor()
	// item.DefaultReviewCount holds the default value on creation for the review_count field.
	item.DefaultReviewCount = itemDescReviewCount.Default.(int)
	// itemDescCreatedAt is the schema descriptor for created_at field.
	itemDescCreatedAt := itemFields[7].Descriptor()
	// item.DefaultCreatedAt holds the default value on creation for the created_at field.
	item.DefaultCreatedAt = itemDescCreatedAt.Default.(func() time.Time)
	// itemDescUpdatedAt is the schema descriptor for updated_at field.
	itemDescUpdatedAt := itemFields[8].Descriptor()
	// item.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	item.DefaultUpdatedAt = itemDescUpdatedAt.Default.(func() time.Time)
	// item.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	item.UpdateDefaultUpdatedAt = itemDescUpdatedAt.UpdateDefault.(func() time.Time)
	// itemDescID is the schema descriptor for id field.
	itemDescID := itemFields[0].Descriptor()
	// item.DefaultID holds the default value on creation for the id field.
	item.DefaultID = itemDescID.Default.(func() string)
}
